# Generated by Django 3.0.7 on 2026-04-28 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=50)),
                ('subject_type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('project', 'Project')], max_length=20)),
                ('l_hours', models.IntegerField(default=0)),
                ('t_hours', models.IntegerField(default=0)),
                ('p_hours', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('cie', models.TextField(blank=True)),
                ('see', models.TextField(blank=True)),
                ('po_count', models.IntegerField(default=12)),
                ('pso_count', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('faculty_approved', 'Faculty Approved'), ('bos_approved', 'BOS Approved'), ('hod_approved', 'HOD Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.Staffs')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('teaching_hours', models.IntegerField(default=0)),
                ('hands_on_exercises', models.TextField(blank=True)),
                ('self_learning', models.TextField(blank=True)),
                ('rbt_level', models.CharField(blank=True, max_length=50)),
                ('books_references', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='student_management_app.Syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='CourseObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_objectives', to='student_management_app.Syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=10)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='student_management_app.Syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='CO_PO_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(choices=[('PO', 'PO'), ('PSO', 'PSO')], max_length=3)),
                ('outcome_number', models.IntegerField()),
                ('mapping_level', models.IntegerField()),
                ('course_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.CourseObjective')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_po_mappings', to='student_management_app.Syllabus')),
            ],
            options={
                'unique_together': {('course_objective', 'outcome_type', 'outcome_number')},
            },
        ),
    ]
