# Generated by Django 3.0.7 on 2026-04-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_approvallog_co_po_mapping_courseobjective_module_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='activity_learning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='cie_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='exam_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='reference_books',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='see_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='see_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='semester',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='textbooks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='web_links',
            field=models.TextField(blank=True),
        ),
    ]
